analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_assert
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_enum_raw_value
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - file_types_order
  - first_where
  - identical_operands
  - implicit_return
  - last_where
  - legacy_objc_type
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - private_subject
  - prohibited_interface_builder
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

disabled_rules:
  - identifier_name
  - inclusive_language
  - trailing_comma
  - conditional_returns_on_newline

cyclomatic_complexity:
  - 20
  - 20

file_length:
  warning: 500
  error: 700

file_types_order:
  order:
    - main_type
    - supporting_type
    - extension
    - previewProvider

function_body_length: 100
function_parameter_count: 6
line_length: 100
type_body_length: 300

large_tuple:
  - 4
  - 4

force_try:
  severity: warning

force_cast:
  severity: warning

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 50
  excluded:
    - T

included:
  - Sources
  - Tests

excluded:
  - Pods

reporter: "xcode"
